name: alte_zimmerei_crew
description: "Mobile app for Alte Zimmerei Crew members"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.1.0
  url_launcher: ^6.2.2
  timeago: ^3.6.0
  uuid: ^4.2.1
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  video_player: ^2.8.1
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

